#!/usr/bin/env bash
# Dracula 主题颜色定义

# 基础颜色
export DRACULA_BACKGROUND="#282a36"
export DRACULA_CURRENT_LINE="#44475a"
export DRACULA_FOREGROUND="#f8f8f2"
export DRACULA_COMMENT="#6272a4"
export DRACULA_CYAN="#8be9fd"
export DRACULA_GREEN="#50fa7b"
export DRACULA_ORANGE="#ffb86c"
export DRACULA_PINK="#ff79c6"
export DRACULA_PURPLE="#bd93f9"
export DRACULA_RED="#ff5555"
export DRACULA_YELLOW="#f1fa8c"

# ANSI 颜色映射
export COLOR_BLACK="$DRACULA_BACKGROUND"
export COLOR_RED="$DRACULA_RED"
export COLOR_GREEN="$DRACULA_GREEN"
export COLOR_YELLOW="$DRACULA_YELLOW"
export COLOR_BLUE="$DRACULA_PURPLE"
export COLOR_MAGENTA="$DRACULA_PINK"
export COLOR_CYAN="$DRACULA_CYAN"
export COLOR_WHITE="$DRACULA_FOREGROUND"

# 亮色版本
export COLOR_BRIGHT_BLACK="$DRACULA_COMMENT"
export COLOR_BRIGHT_RED="$DRACULA_RED"
export COLOR_BRIGHT_GREEN="$DRACULA_GREEN"
export COLOR_BRIGHT_YELLOW="$DRACULA_YELLOW"
export COLOR_BRIGHT_BLUE="$DRACULA_PURPLE"
export COLOR_BRIGHT_MAGENTA="$DRACULA_PINK"
export COLOR_BRIGHT_CYAN="$DRACULA_CYAN"
export COLOR_BRIGHT_WHITE="$DRACULA_FOREGROUND"

# 特殊用途
export COLOR_SELECTION="$DRACULA_CURRENT_LINE"
export COLOR_CURSOR="$DRACULA_FOREGROUND"